-- MySQL Script generated by MySQL Workbench
-- dim. 05 janv. 2020 03:02:34 WET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`catalogue`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`catalogue` ;

CREATE TABLE IF NOT EXISTS `mydb`.`catalogue` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `prix_ht` DECIMAL(5,2) NULL,
  `tva` DECIMAL(5,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`role` ;

CREATE TABLE IF NOT EXISTS `mydb`.`role` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`utilisateur` ;

CREATE TABLE IF NOT EXISTS `mydb`.`utilisateur` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `date_inscription` DATE NULL,
  `email` VARCHAR(45) NULL,
  `telephone` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `nom` VARCHAR(45) NULL,
  `sexe` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `rue` VARCHAR(45) NULL,
  `code_postal` VARCHAR(45) NULL,
  `ville` VARCHAR(45) NULL,
  `role_id` INT(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_utilisateur_role1_idx` (`role_id` ASC),
  CONSTRAINT `fk_utilisateur_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `mydb`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`commande`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`commande` ;

CREATE TABLE IF NOT EXISTS `mydb`.`commande` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `date` DATETIME NULL,
  `etat` VARCHAR(45) NULL,
  `utilisateur_id` INT(10) NOT NULL,
  PRIMARY KEY (`id`, `utilisateur_id`),
  INDEX `fk_commande_utilisateur1_idx` (`utilisateur_id` ASC),
  CONSTRAINT `fk_commande_utilisateur1`
    FOREIGN KEY (`utilisateur_id`)
    REFERENCES `mydb`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ligne_commande`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ligne_commande` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ligne_commande` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `quantite` INT(10) NULL,
  `prix_ht` DECIMAL(5,2) NULL,
  `tva100` DECIMAL(5,2) NULL,
  `commande_id` INT(10) NOT NULL,
  PRIMARY KEY (`id`, `commande_id`),
  INDEX `fk_ligne_commande_commande1_idx` (`commande_id` ASC),
  CONSTRAINT `fk_ligne_commande_commande1`
    FOREIGN KEY (`commande_id`)
    REFERENCES `mydb`.`commande` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pizza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pizza` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pizza` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `catalogue_id` INT(10) NOT NULL,
  `ligne_commande_id` INT(10) NOT NULL,
  PRIMARY KEY (`id`, `catalogue_id`, `ligne_commande_id`),
  INDEX `fk_pizza_catalogue1_idx` (`catalogue_id` ASC),
  INDEX `fk_pizza_ligne_commande1_idx` (`ligne_commande_id` ASC),
  CONSTRAINT `fk_pizza_catalogue1`
    FOREIGN KEY (`catalogue_id`)
    REFERENCES `mydb`.`catalogue` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pizza_ligne_commande1`
    FOREIGN KEY (`ligne_commande_id`)
    REFERENCES `mydb`.`ligne_commande` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recette`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`recette` ;

CREATE TABLE IF NOT EXISTS `mydb`.`recette` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `instructions` TEXT NULL,
  `catalogue_id` INT(10) NOT NULL,
  PRIMARY KEY (`id`, `catalogue_id`),
  INDEX `fk_recette_catalogue1_idx` (`catalogue_id` ASC),
  CONSTRAINT `fk_recette_catalogue1`
    FOREIGN KEY (`catalogue_id`)
    REFERENCES `mydb`.`catalogue` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ingredient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ingredient` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ingredient` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `stock` INT(10) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recette_has_ingredient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`recette_has_ingredient` ;

CREATE TABLE IF NOT EXISTS `mydb`.`recette_has_ingredient` (
  `recette_id` INT NOT NULL,
  `ingredient_id` INT NOT NULL,
  `quantite` INT(10) NULL,
  PRIMARY KEY (`recette_id`, `ingredient_id`),
  INDEX `fk_recette_has_ingredient_ingredient1_idx` (`ingredient_id` ASC),
  INDEX `fk_recette_has_ingredient_recette1_idx` (`recette_id` ASC),
  CONSTRAINT `fk_recette_has_ingredient_recette1`
    FOREIGN KEY (`recette_id`)
    REFERENCES `mydb`.`recette` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recette_has_ingredient_ingredient1`
    FOREIGN KEY (`ingredient_id`)
    REFERENCES `mydb`.`ingredient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`scooter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`scooter` ;

CREATE TABLE IF NOT EXISTS `mydb`.`scooter` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `panne` TINYINT NULL,
  `longitude` DECIMAL(10,8) NULL,
  `latitude` DECIMAL(10,8) NULL,
  `numero_serie` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`livreur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`livreur` ;

CREATE TABLE IF NOT EXISTS `mydb`.`livreur` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `prenom` VARCHAR(45) NULL,
  `nom` VARCHAR(45) NULL,
  `scooter_id` INT(10) NOT NULL,
  PRIMARY KEY (`id`, `scooter_id`),
  INDEX `fk_livreur_scooter1_idx` (`scooter_id` ASC),
  CONSTRAINT `fk_livreur_scooter1`
    FOREIGN KEY (`scooter_id`)
    REFERENCES `mydb`.`scooter` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`livraison`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`livraison` ;

CREATE TABLE IF NOT EXISTS `mydb`.`livraison` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `date` DATETIME NULL,
  `livreur_id` INT(10) NOT NULL,
  `utilisateur_id` INT(10) NOT NULL,
  PRIMARY KEY (`id`, `livreur_id`, `utilisateur_id`),
  INDEX `fk_livraison_livreur1_idx` (`livreur_id` ASC),
  INDEX `fk_livraison_utilisateur1_idx` (`utilisateur_id` ASC),
  CONSTRAINT `fk_livraison_livreur1`
    FOREIGN KEY (`livreur_id`)
    REFERENCES `mydb`.`livreur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livraison_utilisateur1`
    FOREIGN KEY (`utilisateur_id`)
    REFERENCES `mydb`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
